version: 2.1
orbs:
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    working_directory: ~/dfweb-v3
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
    parallelism: 6
